### ISSUE TITLE
Recommended publication to NuGet for easy prototyping

### ISSUE THREAD

**Issue by NighthowlerStudios** [japajoe/LuaNET#1]
.NET is a platform that is quite difficult to use a build system such as CMake for.

However, the easiest option to make this fork available to the public would be to publish it to NuGet yourself.

NuGet makes it easy to pull in and install the package into a codebase for Visual Studio, which reduces development time for prototyping purpose.  Someone more skilled or knowledgeable would obviously script their own build system tool of choice instead.

I understand if you wish not to do this, it is a personal preference of mine to use NuGet for off-the-ground work, and would prefer to see this package used instead of the default Lua.NET.

**Comment by japajoe** [comment]
I'll have to do some research on how to do this because I've never made any NuGet packages myself. I do think it sounds like a good idea and it would give this library a wider reach.

**Comment by japajoe** [comment]
The package should now be available at https://www.nuget.org/packages/JAJ.Packages.LuaNET

If you experience problems please open another issue. Thanks for your interest.

**Comment by NighthowlerStudios** [comment]
Great to hear, thank you for this
